config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_restaurant
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_with
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class= "m-2 p-2">
  <h1>Edit task</h1>

  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.check_box :completed %>
    <%= f.label :completed, "Completed" %>
    <%= f.submit %>
  <% end %>

  <hr />

  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class= "m-2 p-2">
  <h1>My tasks</h1>

  <% @tasks.each do |task| %>
    <% if task.completed %>
      <div class="d-felx">
        <i class="fa-regular fa-square-check"></i>
        <%= link_to task.title, task_path(task) %>
        <%= link_to task_path(task),
        data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
        <i class="fa-solid fa-trash-can"></i>
        <% end %>
      </div>
    <% else %>
      <div class="task-list">
        <i class="fa-regular fa-square"></i>
        <%= link_to task.title, task_path(task) %>
        <%= link_to task_path(task),
        data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
        <i class="fa-solid fa-trash-can"></i>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <hr />

  <%= link_to "Add a new task", tasks_new_path %>

</div>

app/views/tasks/new.html.erb
<div class= "m-2 p-2">
  <h1>New task</h1>

  <%= form_with model: @task do |f| %>
    <div class="form-group mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
    </div>
    <div class="mb-4">
    <%= f.submit %>
    </div>
  <% end %>

  <hr />

  <%= link_to "Back to list", tasks_path %>
<div/>

app/views/tasks/show.html.erb
<div class= "m-2 p-2">
  <h2><%= @task.title %></h2>
  <div class="border mb-3 py-3 ps-3" style="background-color: #F5F5F5;">
    <p class="my-auto"><%= @task.details %></p>
  </div>

  <% if @task.completed %>
      <div class="d-flex align-items-center">
        <i class="fa-regular fa-square-check"></i>
        <p class="my-auto ms-1">This task is completed</p>
      </div>
  <% else %>
      <div class="d-flex align-items-center">
        <i class="fa-regular fa-square"></i>
        <p class="my-auto">This task is not completed yet</p>
      </div>
  <% end %>

  <hr />

  <div class="d-flex">
    <div>
    <%= link_to "Edit this task", edit_restaurant_path %>
    </div>
    <div class="ms-3">
    <%= link_to "Back to list", tasks_path %>
    </div>
  </div>
</div>